const List<String> BASE_OILS = [
  "Grapeseed",
  "Walnut", 
  "Palm", 
  "Cottonseed", 
  "Avocado", 
  "Coconut",
  "Soybean",
  "Olive",
  "Hempseed",
  "Corn",
  "Canola",
  "Flaxseed",
  "Brazilnut",
  "Sunflower",
  "Safflower",
];

const List<String> ESSENTIAL_OILS = [
  "Allspice",
  "Angelica",
  "Anise",
  "Basil",
  "Bay",
  "Benzoin",
  "Bergamot",
  "Birch",
  "Bitter Almond",
  "Black Pepper",
  "Boldo",
  "Buchu",
  "Cajuput",
  "Calamus",
  "Camomile",
  "Camphor",
  "Caraway",
  "Cardamom",
  "Carrot Seed",
  "Cassia",
  "Catnip",
  "Cedarwood",
  "Cinnamon",
  "Citronella",
  "Clary Sage",
  "Clove",
  "Coriander",
  "Cumin",
  "Cypress",
  "Davana",
  "Dill",
  "Elemi",
  "Eucalyptus",
  "Fennel",
  "Frankincense",
  "Galbanum",
  "Geranium",
  "Ginger",
  "Grapefruit",
  "Helichrysum",
  "Hyssop",
  "Jasmine",
  "Juniper",
  "Lavandin",
  "Lavender",
  "Lemon",
  "Lemongrass",
  "Lime",
  "Mandarin",
  "Manuka",
  "Marjoram",
  "Melissa",
  "Mugwort",
  "Mullein",
  "Mustard",
  "Myrrh",
  "Myrtle",
  "Neroli",
  "Niaouli",
  "Nutmeg",
  "Oakmoss",
  "Orange",
  "Oregano",
  "Palma Rosa",
  "Parsley",
  "Patchouli",
  "Pennyroyal",
  "Peppermint",
  "Petitgrain",
  "Pimento",
  "Pine",
  "Ravensara",
  "Rose",
  "Rosemary",
  "Rosewood",
  "Rue",
  "Sage",
  "Sandalwood",
  "Spearmint",
  "Spikenard",
  "Tagetes",
  "Tangerine",
  "Tansy",
  "Tarragon",
  "Tea Tree",
  "Thuja",
  "Thyme",
  "Tuberose",
  "Vanilla",
  "Vetiver",
  "Wintergreen",
  "Wormwood",
  "Yarrow",
  "Ylang Ylang",
];

const List<String> APPLICATIONS = [
  "Massage",
  "Spray",
  "Aromatherapy",
  "Compress",
  "Cream",
  "Diffusion",
];

const List<String> EMOTIONS = [
  'Stress', 
  'Fatigue', 
  'Depression', 
  'Anxiety',
  'Insomnia'
];
